trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_SCANNER_MODE: 'CLI'
  DOCKER_IMAGE_NAME: 'myapp'
  VM_USERNAME: 'azureuser'
  VM_IP: '172.200.134.353'

# Step 1: Checkout code
steps:
  - checkout: self

  # Step 2: Run SonarQube Analysis
  - task: SonarQubePrepare@6
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'CLI'
      configMode: 'file'
      cliProjectKey: 'testazurepipeline'
      cliProjectName: 'Azure Pipeline'
      cliProjectVersion: '1.0'
      cliSources: '.'
      serverUrl: 'http://172.200.134.35:9000'
      sonar.projectKey: 'testazurepipeline'
      sonar.projectName: 'Azure Pipeline'
      sonar.projectVersion: '1.0'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  - script: |
      ~/sonar-scanner-6.0.0.4432-linux/bin/sonar-scanner -X -Dsonar.verbose=true \
        -Dsonar.projectKey=testazurepipeline \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://172.200.134.35:9000
    displayName: 'Run SonarScanner CLI'

  - task: SonarQubeAnalyze@6
    inputs:
      projectKey: 'testazurepipeline'
      sonar.projectKey: 'testazurepipeline'
      options: '-X'
    displayName: 'Run SonarQube Analysis'

  # Step 3: Build Docker Image
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Registry'
      repository: '$(DOCKER_IMAGE_NAME)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        latest

  # Step 4: SSH and Deploy Dockerized App to Azure VM
  - script: |
      ssh -o StrictHostKeyChecking=no $(VM_USERNAME)@$(VM_IP) "docker pull $(DOCKER_IMAGE_NAME):latest && docker run -d -p 80:80 $(DOCKER_IMAGE_NAME):latest"
    displayName: 'Deploy Docker Container to Azure VM'